/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BottoneCalltoaction {
    }
    interface ContainerBody {
    }
    interface ContattiNavigazione {
    }
    interface HeaderPrincipale {
    }
    interface ImgLogo {
    }
    interface ListaContatti {
    }
    interface MenuPrincipale {
    }
    interface NavigazionePrincipale {
    }
    interface TestoCalltoaction {
    }
    interface TestoContatti {
    }
    interface VociMenu {
    }
}
declare global {
    interface HTMLBottoneCalltoactionElement extends Components.BottoneCalltoaction, HTMLStencilElement {
    }
    var HTMLBottoneCalltoactionElement: {
        prototype: HTMLBottoneCalltoactionElement;
        new (): HTMLBottoneCalltoactionElement;
    };
    interface HTMLContainerBodyElement extends Components.ContainerBody, HTMLStencilElement {
    }
    var HTMLContainerBodyElement: {
        prototype: HTMLContainerBodyElement;
        new (): HTMLContainerBodyElement;
    };
    interface HTMLContattiNavigazioneElement extends Components.ContattiNavigazione, HTMLStencilElement {
    }
    var HTMLContattiNavigazioneElement: {
        prototype: HTMLContattiNavigazioneElement;
        new (): HTMLContattiNavigazioneElement;
    };
    interface HTMLHeaderPrincipaleElement extends Components.HeaderPrincipale, HTMLStencilElement {
    }
    var HTMLHeaderPrincipaleElement: {
        prototype: HTMLHeaderPrincipaleElement;
        new (): HTMLHeaderPrincipaleElement;
    };
    interface HTMLImgLogoElement extends Components.ImgLogo, HTMLStencilElement {
    }
    var HTMLImgLogoElement: {
        prototype: HTMLImgLogoElement;
        new (): HTMLImgLogoElement;
    };
    interface HTMLListaContattiElement extends Components.ListaContatti, HTMLStencilElement {
    }
    var HTMLListaContattiElement: {
        prototype: HTMLListaContattiElement;
        new (): HTMLListaContattiElement;
    };
    interface HTMLMenuPrincipaleElement extends Components.MenuPrincipale, HTMLStencilElement {
    }
    var HTMLMenuPrincipaleElement: {
        prototype: HTMLMenuPrincipaleElement;
        new (): HTMLMenuPrincipaleElement;
    };
    interface HTMLNavigazionePrincipaleElement extends Components.NavigazionePrincipale, HTMLStencilElement {
    }
    var HTMLNavigazionePrincipaleElement: {
        prototype: HTMLNavigazionePrincipaleElement;
        new (): HTMLNavigazionePrincipaleElement;
    };
    interface HTMLTestoCalltoactionElement extends Components.TestoCalltoaction, HTMLStencilElement {
    }
    var HTMLTestoCalltoactionElement: {
        prototype: HTMLTestoCalltoactionElement;
        new (): HTMLTestoCalltoactionElement;
    };
    interface HTMLTestoContattiElement extends Components.TestoContatti, HTMLStencilElement {
    }
    var HTMLTestoContattiElement: {
        prototype: HTMLTestoContattiElement;
        new (): HTMLTestoContattiElement;
    };
    interface HTMLVociMenuElement extends Components.VociMenu, HTMLStencilElement {
    }
    var HTMLVociMenuElement: {
        prototype: HTMLVociMenuElement;
        new (): HTMLVociMenuElement;
    };
    interface HTMLElementTagNameMap {
        "bottone-calltoaction": HTMLBottoneCalltoactionElement;
        "container-body": HTMLContainerBodyElement;
        "contatti-navigazione": HTMLContattiNavigazioneElement;
        "header-principale": HTMLHeaderPrincipaleElement;
        "img-logo": HTMLImgLogoElement;
        "lista-contatti": HTMLListaContattiElement;
        "menu-principale": HTMLMenuPrincipaleElement;
        "navigazione-principale": HTMLNavigazionePrincipaleElement;
        "testo-calltoaction": HTMLTestoCalltoactionElement;
        "testo-contatti": HTMLTestoContattiElement;
        "voci-menu": HTMLVociMenuElement;
    }
}
declare namespace LocalJSX {
    interface BottoneCalltoaction {
    }
    interface ContainerBody {
    }
    interface ContattiNavigazione {
    }
    interface HeaderPrincipale {
    }
    interface ImgLogo {
    }
    interface ListaContatti {
    }
    interface MenuPrincipale {
    }
    interface NavigazionePrincipale {
    }
    interface TestoCalltoaction {
    }
    interface TestoContatti {
    }
    interface VociMenu {
    }
    interface IntrinsicElements {
        "bottone-calltoaction": BottoneCalltoaction;
        "container-body": ContainerBody;
        "contatti-navigazione": ContattiNavigazione;
        "header-principale": HeaderPrincipale;
        "img-logo": ImgLogo;
        "lista-contatti": ListaContatti;
        "menu-principale": MenuPrincipale;
        "navigazione-principale": NavigazionePrincipale;
        "testo-calltoaction": TestoCalltoaction;
        "testo-contatti": TestoContatti;
        "voci-menu": VociMenu;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bottone-calltoaction": LocalJSX.BottoneCalltoaction & JSXBase.HTMLAttributes<HTMLBottoneCalltoactionElement>;
            "container-body": LocalJSX.ContainerBody & JSXBase.HTMLAttributes<HTMLContainerBodyElement>;
            "contatti-navigazione": LocalJSX.ContattiNavigazione & JSXBase.HTMLAttributes<HTMLContattiNavigazioneElement>;
            "header-principale": LocalJSX.HeaderPrincipale & JSXBase.HTMLAttributes<HTMLHeaderPrincipaleElement>;
            "img-logo": LocalJSX.ImgLogo & JSXBase.HTMLAttributes<HTMLImgLogoElement>;
            "lista-contatti": LocalJSX.ListaContatti & JSXBase.HTMLAttributes<HTMLListaContattiElement>;
            "menu-principale": LocalJSX.MenuPrincipale & JSXBase.HTMLAttributes<HTMLMenuPrincipaleElement>;
            "navigazione-principale": LocalJSX.NavigazionePrincipale & JSXBase.HTMLAttributes<HTMLNavigazionePrincipaleElement>;
            "testo-calltoaction": LocalJSX.TestoCalltoaction & JSXBase.HTMLAttributes<HTMLTestoCalltoactionElement>;
            "testo-contatti": LocalJSX.TestoContatti & JSXBase.HTMLAttributes<HTMLTestoContattiElement>;
            "voci-menu": LocalJSX.VociMenu & JSXBase.HTMLAttributes<HTMLVociMenuElement>;
        }
    }
}
