/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BannerPreventivo {
    }
    interface BckContattaci {
    }
    interface BottoneFaq {
    }
    interface CampoContattaci {
    }
    interface ContainerBody {
    }
    interface ContainerFaq {
    }
    interface ContainerMobile {
    }
    interface ContattaciForm {
    }
    interface ContattiNavigazione {
    }
    interface DidascaliaFooter {
    }
    interface FooterFooter {
    }
    interface HeaderPrincipale {
    }
    interface ImgLogo {
    }
    interface ListaContatti {
    }
    interface MenuMobile {
        "simpleText": string;
    }
    interface MenuPrincipale {
    }
    interface NavigazionePrincipale {
    }
    interface OggettoMessaggio {
    }
    interface TestoCalltoaction {
    }
    interface TestoContattaci {
    }
    interface TestoContatti {
    }
}
declare global {
    interface HTMLBannerPreventivoElement extends Components.BannerPreventivo, HTMLStencilElement {
    }
    var HTMLBannerPreventivoElement: {
        prototype: HTMLBannerPreventivoElement;
        new (): HTMLBannerPreventivoElement;
    };
    interface HTMLBckContattaciElement extends Components.BckContattaci, HTMLStencilElement {
    }
    var HTMLBckContattaciElement: {
        prototype: HTMLBckContattaciElement;
        new (): HTMLBckContattaciElement;
    };
    interface HTMLBottoneFaqElement extends Components.BottoneFaq, HTMLStencilElement {
    }
    var HTMLBottoneFaqElement: {
        prototype: HTMLBottoneFaqElement;
        new (): HTMLBottoneFaqElement;
    };
    interface HTMLCampoContattaciElement extends Components.CampoContattaci, HTMLStencilElement {
    }
    var HTMLCampoContattaciElement: {
        prototype: HTMLCampoContattaciElement;
        new (): HTMLCampoContattaciElement;
    };
    interface HTMLContainerBodyElement extends Components.ContainerBody, HTMLStencilElement {
    }
    var HTMLContainerBodyElement: {
        prototype: HTMLContainerBodyElement;
        new (): HTMLContainerBodyElement;
    };
    interface HTMLContainerFaqElement extends Components.ContainerFaq, HTMLStencilElement {
    }
    var HTMLContainerFaqElement: {
        prototype: HTMLContainerFaqElement;
        new (): HTMLContainerFaqElement;
    };
    interface HTMLContainerMobileElement extends Components.ContainerMobile, HTMLStencilElement {
    }
    var HTMLContainerMobileElement: {
        prototype: HTMLContainerMobileElement;
        new (): HTMLContainerMobileElement;
    };
    interface HTMLContattaciFormElement extends Components.ContattaciForm, HTMLStencilElement {
    }
    var HTMLContattaciFormElement: {
        prototype: HTMLContattaciFormElement;
        new (): HTMLContattaciFormElement;
    };
    interface HTMLContattiNavigazioneElement extends Components.ContattiNavigazione, HTMLStencilElement {
    }
    var HTMLContattiNavigazioneElement: {
        prototype: HTMLContattiNavigazioneElement;
        new (): HTMLContattiNavigazioneElement;
    };
    interface HTMLDidascaliaFooterElement extends Components.DidascaliaFooter, HTMLStencilElement {
    }
    var HTMLDidascaliaFooterElement: {
        prototype: HTMLDidascaliaFooterElement;
        new (): HTMLDidascaliaFooterElement;
    };
    interface HTMLFooterFooterElement extends Components.FooterFooter, HTMLStencilElement {
    }
    var HTMLFooterFooterElement: {
        prototype: HTMLFooterFooterElement;
        new (): HTMLFooterFooterElement;
    };
    interface HTMLHeaderPrincipaleElement extends Components.HeaderPrincipale, HTMLStencilElement {
    }
    var HTMLHeaderPrincipaleElement: {
        prototype: HTMLHeaderPrincipaleElement;
        new (): HTMLHeaderPrincipaleElement;
    };
    interface HTMLImgLogoElement extends Components.ImgLogo, HTMLStencilElement {
    }
    var HTMLImgLogoElement: {
        prototype: HTMLImgLogoElement;
        new (): HTMLImgLogoElement;
    };
    interface HTMLListaContattiElement extends Components.ListaContatti, HTMLStencilElement {
    }
    var HTMLListaContattiElement: {
        prototype: HTMLListaContattiElement;
        new (): HTMLListaContattiElement;
    };
    interface HTMLMenuMobileElement extends Components.MenuMobile, HTMLStencilElement {
    }
    var HTMLMenuMobileElement: {
        prototype: HTMLMenuMobileElement;
        new (): HTMLMenuMobileElement;
    };
    interface HTMLMenuPrincipaleElement extends Components.MenuPrincipale, HTMLStencilElement {
    }
    var HTMLMenuPrincipaleElement: {
        prototype: HTMLMenuPrincipaleElement;
        new (): HTMLMenuPrincipaleElement;
    };
    interface HTMLNavigazionePrincipaleElement extends Components.NavigazionePrincipale, HTMLStencilElement {
    }
    var HTMLNavigazionePrincipaleElement: {
        prototype: HTMLNavigazionePrincipaleElement;
        new (): HTMLNavigazionePrincipaleElement;
    };
    interface HTMLOggettoMessaggioElement extends Components.OggettoMessaggio, HTMLStencilElement {
    }
    var HTMLOggettoMessaggioElement: {
        prototype: HTMLOggettoMessaggioElement;
        new (): HTMLOggettoMessaggioElement;
    };
    interface HTMLTestoCalltoactionElement extends Components.TestoCalltoaction, HTMLStencilElement {
    }
    var HTMLTestoCalltoactionElement: {
        prototype: HTMLTestoCalltoactionElement;
        new (): HTMLTestoCalltoactionElement;
    };
    interface HTMLTestoContattaciElement extends Components.TestoContattaci, HTMLStencilElement {
    }
    var HTMLTestoContattaciElement: {
        prototype: HTMLTestoContattaciElement;
        new (): HTMLTestoContattaciElement;
    };
    interface HTMLTestoContattiElement extends Components.TestoContatti, HTMLStencilElement {
    }
    var HTMLTestoContattiElement: {
        prototype: HTMLTestoContattiElement;
        new (): HTMLTestoContattiElement;
    };
    interface HTMLElementTagNameMap {
        "banner-preventivo": HTMLBannerPreventivoElement;
        "bck-contattaci": HTMLBckContattaciElement;
        "bottone-faq": HTMLBottoneFaqElement;
        "campo-contattaci": HTMLCampoContattaciElement;
        "container-body": HTMLContainerBodyElement;
        "container-faq": HTMLContainerFaqElement;
        "container-mobile": HTMLContainerMobileElement;
        "contattaci-form": HTMLContattaciFormElement;
        "contatti-navigazione": HTMLContattiNavigazioneElement;
        "didascalia-footer": HTMLDidascaliaFooterElement;
        "footer-footer": HTMLFooterFooterElement;
        "header-principale": HTMLHeaderPrincipaleElement;
        "img-logo": HTMLImgLogoElement;
        "lista-contatti": HTMLListaContattiElement;
        "menu-mobile": HTMLMenuMobileElement;
        "menu-principale": HTMLMenuPrincipaleElement;
        "navigazione-principale": HTMLNavigazionePrincipaleElement;
        "oggetto-messaggio": HTMLOggettoMessaggioElement;
        "testo-calltoaction": HTMLTestoCalltoactionElement;
        "testo-contattaci": HTMLTestoContattaciElement;
        "testo-contatti": HTMLTestoContattiElement;
    }
}
declare namespace LocalJSX {
    interface BannerPreventivo {
    }
    interface BckContattaci {
    }
    interface BottoneFaq {
    }
    interface CampoContattaci {
    }
    interface ContainerBody {
    }
    interface ContainerFaq {
    }
    interface ContainerMobile {
    }
    interface ContattaciForm {
    }
    interface ContattiNavigazione {
    }
    interface DidascaliaFooter {
    }
    interface FooterFooter {
    }
    interface HeaderPrincipale {
    }
    interface ImgLogo {
    }
    interface ListaContatti {
    }
    interface MenuMobile {
        "simpleText"?: string;
    }
    interface MenuPrincipale {
    }
    interface NavigazionePrincipale {
    }
    interface OggettoMessaggio {
    }
    interface TestoCalltoaction {
    }
    interface TestoContattaci {
    }
    interface TestoContatti {
    }
    interface IntrinsicElements {
        "banner-preventivo": BannerPreventivo;
        "bck-contattaci": BckContattaci;
        "bottone-faq": BottoneFaq;
        "campo-contattaci": CampoContattaci;
        "container-body": ContainerBody;
        "container-faq": ContainerFaq;
        "container-mobile": ContainerMobile;
        "contattaci-form": ContattaciForm;
        "contatti-navigazione": ContattiNavigazione;
        "didascalia-footer": DidascaliaFooter;
        "footer-footer": FooterFooter;
        "header-principale": HeaderPrincipale;
        "img-logo": ImgLogo;
        "lista-contatti": ListaContatti;
        "menu-mobile": MenuMobile;
        "menu-principale": MenuPrincipale;
        "navigazione-principale": NavigazionePrincipale;
        "oggetto-messaggio": OggettoMessaggio;
        "testo-calltoaction": TestoCalltoaction;
        "testo-contattaci": TestoContattaci;
        "testo-contatti": TestoContatti;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "banner-preventivo": LocalJSX.BannerPreventivo & JSXBase.HTMLAttributes<HTMLBannerPreventivoElement>;
            "bck-contattaci": LocalJSX.BckContattaci & JSXBase.HTMLAttributes<HTMLBckContattaciElement>;
            "bottone-faq": LocalJSX.BottoneFaq & JSXBase.HTMLAttributes<HTMLBottoneFaqElement>;
            "campo-contattaci": LocalJSX.CampoContattaci & JSXBase.HTMLAttributes<HTMLCampoContattaciElement>;
            "container-body": LocalJSX.ContainerBody & JSXBase.HTMLAttributes<HTMLContainerBodyElement>;
            "container-faq": LocalJSX.ContainerFaq & JSXBase.HTMLAttributes<HTMLContainerFaqElement>;
            "container-mobile": LocalJSX.ContainerMobile & JSXBase.HTMLAttributes<HTMLContainerMobileElement>;
            "contattaci-form": LocalJSX.ContattaciForm & JSXBase.HTMLAttributes<HTMLContattaciFormElement>;
            "contatti-navigazione": LocalJSX.ContattiNavigazione & JSXBase.HTMLAttributes<HTMLContattiNavigazioneElement>;
            "didascalia-footer": LocalJSX.DidascaliaFooter & JSXBase.HTMLAttributes<HTMLDidascaliaFooterElement>;
            "footer-footer": LocalJSX.FooterFooter & JSXBase.HTMLAttributes<HTMLFooterFooterElement>;
            "header-principale": LocalJSX.HeaderPrincipale & JSXBase.HTMLAttributes<HTMLHeaderPrincipaleElement>;
            "img-logo": LocalJSX.ImgLogo & JSXBase.HTMLAttributes<HTMLImgLogoElement>;
            "lista-contatti": LocalJSX.ListaContatti & JSXBase.HTMLAttributes<HTMLListaContattiElement>;
            "menu-mobile": LocalJSX.MenuMobile & JSXBase.HTMLAttributes<HTMLMenuMobileElement>;
            "menu-principale": LocalJSX.MenuPrincipale & JSXBase.HTMLAttributes<HTMLMenuPrincipaleElement>;
            "navigazione-principale": LocalJSX.NavigazionePrincipale & JSXBase.HTMLAttributes<HTMLNavigazionePrincipaleElement>;
            "oggetto-messaggio": LocalJSX.OggettoMessaggio & JSXBase.HTMLAttributes<HTMLOggettoMessaggioElement>;
            "testo-calltoaction": LocalJSX.TestoCalltoaction & JSXBase.HTMLAttributes<HTMLTestoCalltoactionElement>;
            "testo-contattaci": LocalJSX.TestoContattaci & JSXBase.HTMLAttributes<HTMLTestoContattaciElement>;
            "testo-contatti": LocalJSX.TestoContatti & JSXBase.HTMLAttributes<HTMLTestoContattiElement>;
        }
    }
}
