/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BckContattaci {
    }
    interface CampoContattaci {
    }
    interface ContainerBody {
    }
    interface ContattaciForm {
    }
    interface ContattiNavigazione {
    }
    interface HeaderPrincipale {
    }
    interface ImgLogo {
    }
    interface ListaContatti {
    }
    interface MenuPrincipale {
    }
    interface NavigazionePrincipale {
    }
    interface OggettoMessaggio {
    }
    interface TestoCalltoaction {
    }
    interface TestoContattaci {
    }
    interface TestoContatti {
    }
    interface VociMenu {
    }
}
declare global {
    interface HTMLBckContattaciElement extends Components.BckContattaci, HTMLStencilElement {
    }
    var HTMLBckContattaciElement: {
        prototype: HTMLBckContattaciElement;
        new (): HTMLBckContattaciElement;
    };
    interface HTMLCampoContattaciElement extends Components.CampoContattaci, HTMLStencilElement {
    }
    var HTMLCampoContattaciElement: {
        prototype: HTMLCampoContattaciElement;
        new (): HTMLCampoContattaciElement;
    };
    interface HTMLContainerBodyElement extends Components.ContainerBody, HTMLStencilElement {
    }
    var HTMLContainerBodyElement: {
        prototype: HTMLContainerBodyElement;
        new (): HTMLContainerBodyElement;
    };
    interface HTMLContattaciFormElement extends Components.ContattaciForm, HTMLStencilElement {
    }
    var HTMLContattaciFormElement: {
        prototype: HTMLContattaciFormElement;
        new (): HTMLContattaciFormElement;
    };
    interface HTMLContattiNavigazioneElement extends Components.ContattiNavigazione, HTMLStencilElement {
    }
    var HTMLContattiNavigazioneElement: {
        prototype: HTMLContattiNavigazioneElement;
        new (): HTMLContattiNavigazioneElement;
    };
    interface HTMLHeaderPrincipaleElement extends Components.HeaderPrincipale, HTMLStencilElement {
    }
    var HTMLHeaderPrincipaleElement: {
        prototype: HTMLHeaderPrincipaleElement;
        new (): HTMLHeaderPrincipaleElement;
    };
    interface HTMLImgLogoElement extends Components.ImgLogo, HTMLStencilElement {
    }
    var HTMLImgLogoElement: {
        prototype: HTMLImgLogoElement;
        new (): HTMLImgLogoElement;
    };
    interface HTMLListaContattiElement extends Components.ListaContatti, HTMLStencilElement {
    }
    var HTMLListaContattiElement: {
        prototype: HTMLListaContattiElement;
        new (): HTMLListaContattiElement;
    };
    interface HTMLMenuPrincipaleElement extends Components.MenuPrincipale, HTMLStencilElement {
    }
    var HTMLMenuPrincipaleElement: {
        prototype: HTMLMenuPrincipaleElement;
        new (): HTMLMenuPrincipaleElement;
    };
    interface HTMLNavigazionePrincipaleElement extends Components.NavigazionePrincipale, HTMLStencilElement {
    }
    var HTMLNavigazionePrincipaleElement: {
        prototype: HTMLNavigazionePrincipaleElement;
        new (): HTMLNavigazionePrincipaleElement;
    };
    interface HTMLOggettoMessaggioElement extends Components.OggettoMessaggio, HTMLStencilElement {
    }
    var HTMLOggettoMessaggioElement: {
        prototype: HTMLOggettoMessaggioElement;
        new (): HTMLOggettoMessaggioElement;
    };
    interface HTMLTestoCalltoactionElement extends Components.TestoCalltoaction, HTMLStencilElement {
    }
    var HTMLTestoCalltoactionElement: {
        prototype: HTMLTestoCalltoactionElement;
        new (): HTMLTestoCalltoactionElement;
    };
    interface HTMLTestoContattaciElement extends Components.TestoContattaci, HTMLStencilElement {
    }
    var HTMLTestoContattaciElement: {
        prototype: HTMLTestoContattaciElement;
        new (): HTMLTestoContattaciElement;
    };
    interface HTMLTestoContattiElement extends Components.TestoContatti, HTMLStencilElement {
    }
    var HTMLTestoContattiElement: {
        prototype: HTMLTestoContattiElement;
        new (): HTMLTestoContattiElement;
    };
    interface HTMLVociMenuElement extends Components.VociMenu, HTMLStencilElement {
    }
    var HTMLVociMenuElement: {
        prototype: HTMLVociMenuElement;
        new (): HTMLVociMenuElement;
    };
    interface HTMLElementTagNameMap {
        "bck-contattaci": HTMLBckContattaciElement;
        "campo-contattaci": HTMLCampoContattaciElement;
        "container-body": HTMLContainerBodyElement;
        "contattaci-form": HTMLContattaciFormElement;
        "contatti-navigazione": HTMLContattiNavigazioneElement;
        "header-principale": HTMLHeaderPrincipaleElement;
        "img-logo": HTMLImgLogoElement;
        "lista-contatti": HTMLListaContattiElement;
        "menu-principale": HTMLMenuPrincipaleElement;
        "navigazione-principale": HTMLNavigazionePrincipaleElement;
        "oggetto-messaggio": HTMLOggettoMessaggioElement;
        "testo-calltoaction": HTMLTestoCalltoactionElement;
        "testo-contattaci": HTMLTestoContattaciElement;
        "testo-contatti": HTMLTestoContattiElement;
        "voci-menu": HTMLVociMenuElement;
    }
}
declare namespace LocalJSX {
    interface BckContattaci {
    }
    interface CampoContattaci {
    }
    interface ContainerBody {
    }
    interface ContattaciForm {
    }
    interface ContattiNavigazione {
    }
    interface HeaderPrincipale {
    }
    interface ImgLogo {
    }
    interface ListaContatti {
    }
    interface MenuPrincipale {
    }
    interface NavigazionePrincipale {
    }
    interface OggettoMessaggio {
    }
    interface TestoCalltoaction {
    }
    interface TestoContattaci {
    }
    interface TestoContatti {
    }
    interface VociMenu {
    }
    interface IntrinsicElements {
        "bck-contattaci": BckContattaci;
        "campo-contattaci": CampoContattaci;
        "container-body": ContainerBody;
        "contattaci-form": ContattaciForm;
        "contatti-navigazione": ContattiNavigazione;
        "header-principale": HeaderPrincipale;
        "img-logo": ImgLogo;
        "lista-contatti": ListaContatti;
        "menu-principale": MenuPrincipale;
        "navigazione-principale": NavigazionePrincipale;
        "oggetto-messaggio": OggettoMessaggio;
        "testo-calltoaction": TestoCalltoaction;
        "testo-contattaci": TestoContattaci;
        "testo-contatti": TestoContatti;
        "voci-menu": VociMenu;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bck-contattaci": LocalJSX.BckContattaci & JSXBase.HTMLAttributes<HTMLBckContattaciElement>;
            "campo-contattaci": LocalJSX.CampoContattaci & JSXBase.HTMLAttributes<HTMLCampoContattaciElement>;
            "container-body": LocalJSX.ContainerBody & JSXBase.HTMLAttributes<HTMLContainerBodyElement>;
            "contattaci-form": LocalJSX.ContattaciForm & JSXBase.HTMLAttributes<HTMLContattaciFormElement>;
            "contatti-navigazione": LocalJSX.ContattiNavigazione & JSXBase.HTMLAttributes<HTMLContattiNavigazioneElement>;
            "header-principale": LocalJSX.HeaderPrincipale & JSXBase.HTMLAttributes<HTMLHeaderPrincipaleElement>;
            "img-logo": LocalJSX.ImgLogo & JSXBase.HTMLAttributes<HTMLImgLogoElement>;
            "lista-contatti": LocalJSX.ListaContatti & JSXBase.HTMLAttributes<HTMLListaContattiElement>;
            "menu-principale": LocalJSX.MenuPrincipale & JSXBase.HTMLAttributes<HTMLMenuPrincipaleElement>;
            "navigazione-principale": LocalJSX.NavigazionePrincipale & JSXBase.HTMLAttributes<HTMLNavigazionePrincipaleElement>;
            "oggetto-messaggio": LocalJSX.OggettoMessaggio & JSXBase.HTMLAttributes<HTMLOggettoMessaggioElement>;
            "testo-calltoaction": LocalJSX.TestoCalltoaction & JSXBase.HTMLAttributes<HTMLTestoCalltoactionElement>;
            "testo-contattaci": LocalJSX.TestoContattaci & JSXBase.HTMLAttributes<HTMLTestoContattaciElement>;
            "testo-contatti": LocalJSX.TestoContatti & JSXBase.HTMLAttributes<HTMLTestoContattiElement>;
            "voci-menu": LocalJSX.VociMenu & JSXBase.HTMLAttributes<HTMLVociMenuElement>;
        }
    }
}
